# Generated by Django 5.1.4 on 2026-03-09 20:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('priority', models.IntegerField(default=5, help_text='1 = highest priority, 10 = lowest priority')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('DEAD', 'Dead (DLQ)'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, help_text='Unique key to prevent duplicate job submissions', max_length=255, null=True, unique=True)),
                ('run_at', models.DateTimeField(blank=True, db_index=True, help_text='If set, job will not execute until this time', null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('worker_id', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', '-created_at'],
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='idx_status_next_retry'), models.Index(fields=['status', 'run_at'], name='idx_status_run_at'), models.Index(fields=['status', 'priority', 'created_at'], name='idx_status_priority_created')],
            },
        ),
    ]
